# Generated by Django 6.0.7 on 2026-07-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('General', 'General'), ('Exam', 'Exam'), ('Event', 'Event'), ('Placement', 'Placement'), ('Holiday', 'Holiday')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
